//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using HalconDotNet;

public partial class HDevelopExport
{
  public HTuple hv_ExpDefaultWinHandle;

  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_ImageFilterEE, ho_EE, ho_ImageFilterSS;
    HObject ho_SS, ho_ImageFilterRR, ho_RR;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ImageFilterEE);
    HOperatorSet.GenEmptyObj(out ho_EE);
    HOperatorSet.GenEmptyObj(out ho_ImageFilterSS);
    HOperatorSet.GenEmptyObj(out ho_SS);
    HOperatorSet.GenEmptyObj(out ho_ImageFilterRR);
    HOperatorSet.GenEmptyObj(out ho_RR);
    ho_ImageFilterEE.Dispose();
    HOperatorSet.GenFilterMask(out ho_ImageFilterEE, "laws_ee", 1.0, 512, 512);
    ho_EE.Dispose();
    HOperatorSet.FftImage(ho_ImageFilterEE, out ho_EE);
    ho_ImageFilterSS.Dispose();
    HOperatorSet.GenFilterMask(out ho_ImageFilterSS, "laws_ss", 1.5, 512, 512);
    ho_SS.Dispose();
    HOperatorSet.FftImage(ho_ImageFilterSS, out ho_SS);
    ho_ImageFilterRR.Dispose();
    HOperatorSet.GenFilterMask(out ho_ImageFilterRR, "laws_rr", 0.1, 512, 512);
    ho_RR.Dispose();
    HOperatorSet.FftImage(ho_ImageFilterRR, out ho_RR);
    ho_ImageFilterEE.Dispose();
    ho_EE.Dispose();
    ho_ImageFilterSS.Dispose();
    ho_SS.Dispose();
    ho_ImageFilterRR.Dispose();
    ho_RR.Dispose();

  }

  public void InitHalcon()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
  }

  public void RunHalcon(HTuple Window)
  {
    hv_ExpDefaultWinHandle = Window;
    action();
  }

}

